# configure the Drone Pipelin
#pipeline:
  #staging-environment: #the name backend can be changed to anything
    #image: phpunit/phpunit
    #commands:
      #- composer install
      #- echo "we the best"
      #- cat index.php
      #- vendor/bin/phpunit Tests/SimplePaginationTest.php
    #when:
      #branch: staging

  #publish:
      #image: plugins/docker
      #repo: chadubab/simplepaginator
      #tags: latest
      #secrets: [ docker_username, docker_password ]


#services:
  #cache:
    #image: composer


pipeline:
  ssh:
    pull: true
    image: appleboy/drone-ssh
    host: 18.223.161.61
    username: ubuntu
    port: 22
    secrets: [ ssh_key ]
    script:
      - echo "test ssh again"
