# configure the Drone Pipelin
pipeline:
  backend:
    image: phpunit/phpunit
    commands:
      - echo "we the best"
      - cat index.php
      #- vendor/bin/phpunit Tests/SimplePaginationTest.php


